CREATE TABLE album_catalogue (
	id INT PRIMARY KEY,
	album_title VARCHAR(120),
	album_length INTERVAL,
	album_genre VARCHAR(120),
	artist VARCHAR(120),
	copies_sold INT,
	sales_period VARCHAR(120)
	
);
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (1,'Wednesday Morning, 3 A.M', '31M 38S', 'Folk', 'Simon & Garfunkel', 1043, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (2,'EnRoute: John Scofield Trio LIVE', '73M 48S', 'Jazz', 'John Scofield Trio', 512, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (3,'Nasty Gal', '39M 15S', 'Funk', 'Betty Davis', 809, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (4,'The New Folk Sound of Terry Callier', '37M 41S', 'Folk', 'Terry Callier', 903, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (5,'In a Silent Way', '38M 08S', 'Jazz', 'Miles Davis', 428, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (6,'Cold Sweat', '33M 43S', 'Funk', 'James Brown', 815, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (7,'The Freewheelin'' Bob Dylan', '44M 14S', 'Folk', 'Bob Dylan', 1008, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (8,'My Favorite Things', '40M 25S', 'Jazz', 'John Coltrane', 325, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (9,'A Whole New Thing', '38M 01S', 'Funk', 'Sly and the Family Stone', 674, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (10,'Five Leaves Left', '41M 43S', 'Folk', 'Nick Drake', 321, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (11,'Head Hunters', '41M 52S', 'Jazz', 'Herbie Hancock', 497, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (12,'In the Right Place', '33M 22S', 'Funk', 'Dr. John', 222, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (13,'Blue', '36M 15S', 'Folk', 'Joni Mitchell', 589, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (14,'Concierto', '38M 02S', 'Jazz', 'Jim Hall', 479, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (15,'Dirty Mind', '30M 14S', 'Funk', 'Prince', 894, '2022_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (16,'Wednesday Morning, 3 A.M', '31M 38S', 'Folk', 'Simon & Garfunkel', 437, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (17,'EnRoute: John Scofield Trio LIVE', '73M 48S', 'Jazz', 'John Scofield Trio', 945, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (18,'Nasty Gal', '39M 15S', 'Funk', 'Betty Davis', 224, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (19,'The New Folk Sound of Terry Callier', '37M 41S', 'Folk', 'Terry Callier', 418, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (20,'In a Silent Way', '38M 08S', 'Jazz', 'Miles Davis', 1053, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (21,'Cold Sweat', '33M 43S', 'Funk', 'James Brown', 1000, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (22,'The Freewheelin'' Bob Dylan', '44M 14S', 'Folk', 'Bob Dylan', 359, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (23,'My Favorite Things', '40M 25S', 'Jazz', 'John Coltrane', 333, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (24,'A Whole New Thing', '38M 01S', 'Funk', 'Sly and the Family Stone', 257, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (25,'Five Leaves Left', '41M 43S', 'Folk', 'Nick Drake', 456, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (26,'Head Hunters', '41M 52S', 'Jazz', 'Herbie Hancock', 411, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (27,'In the Right Place', '33M 22S', 'Funk', 'Dr. John', 208, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (28,'Blue', '36M 15S', 'Folk', 'Joni Mitchell', 184, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (29,'Concierto', '38M 02S', 'Jazz', 'Jim Hall', 288, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (30,'Dirty Mind', '30M 14S', 'Funk', 'Prince', 1008, '2022_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (31,'Wednesday Morning, 3 A.M', '31M 38S', 'Folk', 'Simon & Garfunkel', 184, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (32,'EnRoute: John Scofield Trio LIVE', '73M 48S', 'Jazz', 'John Scofield Trio', 256, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (33,'Nasty Gal', '39M 15S', 'Funk', 'Betty Davis', 228, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (34,'The New Folk Sound of Terry Callier', '37M 41S', 'Folk', 'Terry Callier', 1254, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (35,'In a Silent Way', '38M 08S', 'Jazz', 'Miles Davis', 19, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (36,'Cold Sweat', '33M 43S', 'Funk', 'James Brown', 29, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (37,'The Freewheelin'' Bob Dylan', '44M 14S', 'Folk', 'Bob Dylan', 100, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (38,'My Favorite Things', '40M 25S', 'Jazz', 'John Coltrane', 349, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (39,'A Whole New Thing', '38M 01S', 'Funk', 'Sly and the Family Stone', 666, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (40,'Five Leaves Left', '41M 43S', 'Folk', 'Nick Drake', 20, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (41,'Head Hunters', '41M 52S', 'Jazz', 'Herbie Hancock', 100, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (42,'In the Right Place', '33M 22S', 'Funk', 'Dr. John', 94, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (43,'Blue', '36M 15S', 'Folk', 'Joni Mitchell', 256, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (44,'Concierto', '38M 02S', 'Jazz', 'Jim Hall', 306, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (45,'Dirty Mind', '30M 14S', 'Funk', 'Prince', 412, '2022_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (46,'Wednesday Morning, 3 A.M', '31M 38S', 'Folk', 'Simon & Garfunkel', 809, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (47,'EnRoute: John Scofield Trio LIVE', '73M 48S', 'Jazz', 'John Scofield Trio', 612, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (48,'Nasty Gal', '39M 15S', 'Funk', 'Betty Davis', 369, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (49,'The New Folk Sound of Terry Callier', '37M 41S', 'Folk', 'Terry Callier', 214, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (50,'In a Silent Way', '38M 08S', 'Jazz', 'Miles Davis', 65, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (51,'Cold Sweat', '33M 43S', 'Funk', 'James Brown', 209, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (52,'The Freewheelin'' Bob Dylan', '44M 14S', 'Folk', 'Bob Dylan', 246, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (53,'My Favorite Things', '40M 25S', 'Jazz', 'John Coltrane', 377, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (54,'A Whole New Thing', '38M 01S', 'Funk', 'Sly and the Family Stone', 816, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (55,'Five Leaves Left', '41M 43S', 'Folk', 'Nick Drake', 400, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (56,'Head Hunters', '41M 52S', 'Jazz', 'Herbie Hancock', 409, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (57,'In the Right Place', '33M 22S', 'Funk', 'Dr. John', 912, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (58,'Blue', '36M 15S', 'Folk', 'Joni Mitchell', 412, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (59,'Concierto', '38M 02S', 'Jazz', 'Jim Hall', 612, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (60,'Dirty Mind', '30M 14S', 'Funk', 'Prince', 941, '2022_4Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (61,'Wednesday Morning, 3 A.M', '31M 38S', 'Folk', 'Simon & Garfunkel', 809, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (62,'EnRoute: John Scofield Trio LIVE', '73M 48S', 'Jazz', 'John Scofield Trio', 612, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (63,'Nasty Gal', '39M 15S', 'Funk', 'Betty Davis', 369, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (64,'The New Folk Sound of Terry Callier', '37M 41S', 'Folk', 'Terry Callier', 214, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (65,'In a Silent Way', '38M 08S', 'Jazz', 'Miles Davis', 65, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (66,'Cold Sweat', '33M 43S', 'Funk', 'James Brown', 209, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (67,'The Freewheelin'' Bob Dylan', '44M 14S', 'Folk', 'Bob Dylan', 246, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (68,'My Favorite Things', '40M 25S', 'Jazz', 'John Coltrane', 377, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (69,'A Whole New Thing', '38M 01S', 'Funk', 'Sly and the Family Stone', 816, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (70,'Five Leaves Left', '41M 43S', 'Folk', 'Nick Drake', 400, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (71,'Head Hunters', '41M 52S', 'Jazz', 'Herbie Hancock', 409, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (72,'In the Right Place', '33M 22S', 'Funk', 'Dr. John', 912, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (73,'Blue', '36M 15S', 'Folk', 'Joni Mitchell', 412, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (74,'Concierto', '38M 02S', 'Jazz', 'Jim Hall', 612, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (75,'Dirty Mind', '30M 14S', 'Funk', 'Prince', 941, '2023_1Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (76,'Wednesday Morning, 3 A.M', '31M 38S', 'Folk', 'Simon & Garfunkel', 325, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (77,'EnRoute: John Scofield Trio LIVE', '73M 48S', 'Jazz', 'John Scofield Trio', 941, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (78,'Nasty Gal', '39M 15S', 'Funk', 'Betty Davis', 555, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (79,'The New Folk Sound of Terry Callier', '37M 41S', 'Folk', 'Terry Callier', 541, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (80,'In a Silent Way', '38M 08S', 'Jazz', 'Miles Davis', 218, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (81,'Cold Sweat', '33M 43S', 'Funk', 'James Brown', 456, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (82,'The Freewheelin'' Bob Dylan', '44M 14S', 'Folk', 'Bob Dylan', 654, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (83,'My Favorite Things', '40M 25S', 'Jazz', 'John Coltrane', 203, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (84,'A Whole New Thing', '38M 01S', 'Funk', 'Sly and the Family Stone', 302, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (85,'Five Leaves Left', '41M 43S', 'Folk', 'Nick Drake', 116, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (86,'Head Hunters', '41M 52S', 'Jazz', 'Herbie Hancock', 245, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (87,'In the Right Place', '33M 22S', 'Funk', 'Dr. John', 56, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (88,'Blue', '36M 15S', 'Folk', 'Joni Mitchell', 99, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (89,'Concierto', '38M 02S', 'Jazz', 'Jim Hall', 145, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (90,'Dirty Mind', '30M 14S', 'Funk', 'Prince', 100, '2023_2Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (91,'Wednesday Morning, 3 A.M', '31M 38S', 'Folk', 'Simon & Garfunkel', 612, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (92,'EnRoute: John Scofield Trio LIVE', '73M 48S', 'Jazz', 'John Scofield Trio', 404, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (93,'Nasty Gal', '39M 15S', 'Funk', 'Betty Davis', 808, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (94,'The New Folk Sound of Terry Callier', '37M 41S', 'Folk', 'Terry Callier', 283, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (95,'In a Silent Way', '38M 08S', 'Jazz', 'Miles Davis', 809, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (96,'Cold Sweat', '33M 43S', 'Funk', 'James Brown', 1005, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (97,'The Freewheelin'' Bob Dylan', '44M 14S', 'Folk', 'Bob Dylan', 597, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (98,'My Favorite Things', '40M 25S', 'Jazz', 'John Coltrane', 302, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (99,'A Whole New Thing', '38M 01S', 'Funk', 'Sly and the Family Stone', 123, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (100,'Five Leaves Left', '41M 43S', 'Folk', 'Nick Drake', 321, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (101,'Head Hunters', '41M 52S', 'Jazz', 'Herbie Hancock', 542, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (102,'In the Right Place', '33M 22S', 'Funk', 'Dr. John', 562, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (103,'Blue', '36M 15S', 'Folk', 'Joni Mitchell', 995, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (104,'Concierto', '38M 02S', 'Jazz', 'Jim Hall', 263, '2023_3Q');
INSERT INTO album_catalogue (id, album_title, album_length, album_genre, artist, copies_sold, sales_period) VALUES (105,'Dirty Mind', '30M 14S', 'Funk', 'Prince', 169, '2023_3Q');
